spring.application.name=book-my-show

spring.datasource.url=jdbc:mysql://localhost:3306/cinemaDb?createTableIfNotExist=true
spring.datasource.username=root
spring.datasource.password=MYSQL123@123
spring.jpa.hibernate.ddl-auto=update

